//! XDR spec fixture test for `create_will`.
//!
//! The `#[contractimpl]` macro emits a `__SPEC_XDR_FN_CREATE_WILL` constant
//! containing the XDR-encoded `ScSpecEntry` for the `create_will` function.
//! This test reads that constant, hex-encodes it, and compares it against the
//! checked-in fixture at `src/fixtures/create_will_spec.txt`.
//!
//! # What this catches
//!
//! Any change to the `create_will` parameter names, types, or order causes
//! the macro to emit a different XDR blob, which will differ from the fixture
//! and fail this test. This surfaces schema drift between the contract and any
//! SDK or client that encodes `create_will` arguments independently
//! (e.g. sorowill-sdk — see companion spec-drift-check in sorowill-sdk#101).
//!
//! # Updating the fixture
//!
//! When you intentionally change the `create_will` signature, run:
//!
//! ```text
//! cargo test -p will --lib test_spec_fixture_create_will_update -- --nocapture
//! ```
//!
//! That test prints the new hex and writes it into the fixture file. Commit
//! both the code change and the updated fixture in the same PR. Coordinate
//! with the SDK repo (sorowill-sdk#101) so both sides stay in sync.

#![cfg(test)]

use crate::WillContract;

/// Hex-encode a byte slice into a lowercase hex string.
fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

/// Path to the fixture file, relative to the crate root at compile time.
const FIXTURE_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/fixtures/create_will_spec.txt"
);

/// The XDR-encoded spec for `create_will`, generated by `#[contractimpl]`.
///
/// `soroban-sdk` 22.x names this constant `__SPEC_XDR_FN_CREATE_WILL` on the
/// contract struct. The slice length is determined at compile time and varies
/// with the function signature.
const SPEC_XDR: &[u8] = &WillContract::spec_xdr_create_will();

/// Verifies that the live spec matches the checked-in fixture.
///
/// If the fixture contains `"GENERATE"`, it is treated as uninitialised and
/// this test writes the current encoding into it (first-run bootstrap), then
/// passes. On every subsequent run the fixture is compared byte-for-byte.
#[test]
fn test_spec_fixture_create_will() {
    let current_hex = to_hex(SPEC_XDR);

    let fixture_content = std::fs::read_to_string(FIXTURE_PATH)
        .unwrap_or_else(|e| panic!("Could not read fixture at {FIXTURE_PATH}: {e}"));

    // Extract the hex line: the last non-comment, non-empty line.
    let fixture_hex = fixture_content
        .lines()
        .rfind(|l| !l.starts_with('#') && !l.is_empty())
        .unwrap_or("")
        .trim()
        .to_owned();

    if fixture_hex == "GENERATE" {
        // First-run bootstrap: write the current encoding into the fixture.
        write_fixture(&current_hex);
        println!("create_will spec fixture initialised:\n{current_hex}");
        return;
    }

    assert_eq!(
        current_hex, fixture_hex,
        "\ncreate_will XDR spec has changed — the contract's API no longer matches \
         the checked-in fixture.\n\
         \n\
         If this change is intentional, run:\n\
         \n  cargo test -p will --lib test_spec_fixture_create_will_update -- --nocapture\n\
         \n\
         to update the fixture, then commit the updated \
         src/fixtures/create_will_spec.txt alongside your code change.\n\
         \n\
         Also coordinate with sorowill-sdk#101 so the SDK's expected encoding \
         is updated in the same release window.\n"
    );
}

/// Updates the fixture file with the current XDR encoding. Run this test
/// explicitly after an intentional signature change to regenerate the fixture:
///
/// ```text
/// cargo test -p will --lib test_spec_fixture_create_will_update -- --nocapture
/// ```
#[test]
fn test_spec_fixture_create_will_update() {
    let current_hex = to_hex(SPEC_XDR);
    write_fixture(&current_hex);
    println!("create_will spec fixture updated:\n{current_hex}");
}

/// Rewrites the fixture file, preserving the header comments and replacing
/// the last (hex/GENERATE) line with `new_hex`.
fn write_fixture(new_hex: &str) {
    let fixture_content = std::fs::read_to_string(FIXTURE_PATH).unwrap_or_default();

    let mut lines: Vec<&str> = fixture_content
        .lines()
        .filter(|l| l.starts_with('#') || l.is_empty())
        .collect();

    // Ensure there is at least the header block.
    if lines.is_empty() {
        lines
            .push("# create_will XDR spec fixture — see test_xdr_spec.rs for update instructions.");
        lines.push("#");
    }

    let mut new_content = lines.join("\n");
    new_content.push('\n');
    new_content.push_str(new_hex);
    new_content.push('\n');

    std::fs::write(FIXTURE_PATH, &new_content)
        .unwrap_or_else(|e| panic!("Could not write fixture at {FIXTURE_PATH}: {e}"));
}
